### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by tclose** [nipype/pydra-mrtrix3#9]
Is there a chance we could create a pydra-mrtrix3 release on PyPI? I realise there is only one task interface implemented but I need it for a dependency

**Comment by tclose** [comment]
Happy to do this if you like

**Comment by effigies** [comment]
Sure, will do that now.

**Comment by satra** [comment]
@effigies - thank you. we should add the whole auto setup to the templates, so that this can be done using github labels on PRs.

**Comment by effigies** [comment]
Not sure what that's referring to. Example?

**Comment by satra** [comment]
this has been implemented in pydra.

> https://github.com/nipype/pydra/blob/master/.github/workflows/release.yml

and more info this thread. https://github.com/nipype/pydra/issues/484
